apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: wordpress
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # "password" in base64
  MYSQL_PASSWORD: cGFzc3dvcmQ=       # "password" in base64
